version: '3.8'
services:
  app:
    container_name: nestjs_app
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://user:password@db:5433/elevcode
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: postgres_db
    image: postgres:13
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: elevcode
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
